export const CHECKING_IN = 'CHECKING_IN';
export const CHECKED_IN = 'CHECKED_IN';
export const SKIPPED_CHECKIN = 'SKIPPED_CHECKIN';
export const UPDATE_CHECKINS = 'UPDATE_CHECKINS';

export const COMPLETING_GOAL = 'COMPLETING_GOAL';
export const CREATING_GOAL = 'CREATING_GOAL';
export const DELETE_GOAL = 'DELETE_GOAL';

export const CANCEL = 'CANCEL';
export const CONFIRM = 'CONFIRM';
export const OPEN_GOAL_POPOVER = 'OPEN_GOAL_POPOVER';
export const HIDE_GOAL_POPOVER = 'HIDE_GOAL_POPOVER';

export const OPEN_CATEGORY = 'OPEN_CATEGORY';

export const OPEN_MENU_POPOVER = 'OPEN_MENU_POPOVER';
export const HIDE_MENU_POPOVER = 'HIDE_MENU_POPOVER';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_NEW_COLOR = 'UPDATE_NEW_COLOR';

export const OPEN_EDIT_CATEGORY = 'OPEN_EDIT_CATEGORY';
export const HIDE_EDIT_CATEGORY = 'HIDE_EDIT_CATEGORY';
export const EDIT_CATEGORY_COLOR = 'EDIT_CATEGORY_COLOR';

export const EDIT_CATEGORY_TITLE = 'EDIT_CATEGORY_TITLE';
export  const DELETE_CATEGORY = 'DELETE_CATEGORY';